version: '3.9'

services:
  postgres:
    image: postgres:13.2
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
      # - ./.env:/docker-entrypoint-initdb.d/.env
      # - ./create_databases.sh:/docker-entrypoint-initdb.d/create_databases.sh
      # - ./permissions.sh:/docker-entrypoint-initdb.d/permissions.sh
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_DB_USERS=${POSTGRES_DB_USERS}
      # - POSTGRES_DB_PRODUCTS=${POSTGRES_DB_PRODUCTS}
    networks:
      - app_network



  
  pg-admin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT = 5050
    ports:
      - 5050:80
    networks:
      - app_network



  nextjs-app:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: nextjs-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    networks:
      - app_network


  rust-user-server:
    build:
      context: ./userserver
      dockerfile: Dockerfile
    container_name: rustserver-dc-users
    ports:
      - 10000:10000
    networks:
      - app_network
    volumes:
      - './userserver:/usr/src/userserver'
      - '/usr/src/userserver/target'
    environment:
      - MY_LOG_LEVEL=info
      - MY_LOG_STYLE=Always
      - USER_DATABASE_URL=${USER_DATABASE_URL}
      - EMAIL_VERIFICATION_SECRET=${EMAIL_VERIFICATION_SECRET}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - RESET_PASSWORD_SECRET=${RESET_PASSWORD_SECRET}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - EMAIL_PASSWORD_SECRET=${EMAIL_PASSWORD_SECRET}

    depends_on:
      - postgres


  rust-products-server:
    build:
      context: ./productsserver
      dockerfile: Dockerfile
    container_name: rustserver-dc-products
    ports:
      - 10010:10010
    networks:
      - app_network
    volumes:
      - './productsserver:/usr/src/productsserver'
      - '/usr/src/productsserver/target'
    environment:
      - MY_LOG_LEVEL=info
      - MY_LOG_STYLE=Always
      - PRODUCTS_DATABASE_URL=${PRODUCTS_DATABASE_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISH_KEY=${STRIPE_PUBLISH_KEY}

    depends_on:
      - postgres


networks:
  app_network:
    driver: bridge
    

volumes:
  data:
