worker_processes 1;

events {
  worker_connections 1024;
}

http {
  sendfile on;

  upstream client {
    server nextjs-app:3000;
  }

  upstream rust {
    server rustserver-dc:10000;
  }

  server {
    listen 80 default_server;

    location / {
      proxy_pass http://client;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/v1 {
      proxy_pass http://rust;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      rewrite /api/v1/(.*) /$1 break;
    }
  }
}
